/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        paper: "var(--color-paper)",
        "paper-2": "var(--color-paper-2)",
        "paper-3": "var(--color-paper-3)",
        "paper-glass": "var(--color-paper-glass)",
        "paper-2-glass": "var(--color-paper-2-glass)",
        "paper-3-glass": "var(--color-paper-3-glass)",
        ink: "var(--color-ink)",
        "ink-2": "var(--color-ink-2)",
        rule: "var(--color-rule)",
        "rule-strong": "var(--color-rule-strong)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-bg": "var(--color-accent-bg)",
        success: "var(--color-success)",
        "success-bg": "var(--color-success-bg)",
        "success-border": "var(--color-success-border)",
        error: "var(--color-error)",
        "error-bg": "var(--color-error-bg)",
        "error-border": "var(--color-error-border)",
        warning: "var(--color-warning)",
        "warning-bg": "var(--color-warning-bg)",
        "warning-border": "var(--color-warning-border)",
        focus: "var(--color-focus)",
      },
    },
  },
  plugins: [],
};
